services:
  rooksafe-back:
    build:
      context: .
    image: igrowker/i004-rooksafe-back
    restart: always
    environment:
      - DJANGO_SUPERUSER_USERNAME=${DJ_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJ_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJ_EMAIL}
      - SECRET_KEY=${SECRET_KEY}
      - EXPERIENCE_LEVEL=${EXPERIENCE_LEVEL}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - YT_API_KEY=${YT_API_KEY}
    working_dir: /usr/share/app
    volumes:
      - static:/usr/share/app/site_app/static
    networks:
      - rooksafe
  rooksafe-proxy:
    container_name: rooksafe-back-proxy
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/my_ginx.conf:/etc/nginx/sites-available/my_ginx.conf
      - static:/app/static
    depends_on:
      - rooksafe-back
    networks:
      - rooksafe

volumes:
  static:

networks:
  rooksafe:
     name: rooksafe
     external: true
